#!/bin/bash

function create_user() {
	useradd -M $uname
	echo "$uname:$pass" | chpasswd
	usermod -e $expdate $uname

	echo ""
	echo -e "\e[92mID $uname telah berjaya dibuat\e[0m"
}

function renew_user() {
	echo "New expiration date for $uname: $expdate...";
	usermod -e $expdate $uname
	
	echo ""
	echo -e "\e[92mID $uname telah berjaya diperbaharui\e[0m"	
}

function delete_user(){
	userdel $uname
	
	echo ""
	echo -e "\e[91mID $uname telah berjaya dibuang\e[0m"
}

function expired_users(){
echo    "---------"
echo -e "\e[31mUSERNAME\e[0m"
echo    "---------"
	cat /etc/shadow | cut -d: -f1,8 | sed /:$/d > /tmp/expirelist.txt
	totalaccounts=`cat /tmp/expirelist.txt | wc -l`
	for((i=1; i<=$totalaccounts; i++ )); do
		tuserval=`head -n $i /tmp/expirelist.txt | tail -n 1`
		username=`echo $tuserval | cut -f1 -d:`
		userexp=`echo $tuserval | cut -f2 -d:`
		userexpireinseconds=$(( $userexp * 86400 ))
		todaystime=`date +%s`
		if [ $userexpireinseconds -lt $todaystime ] ; then
			echo $username
		fi
	done
	rm /tmp/expirelist.txt
}

function not_expired_users(){
echo    "---------"
echo -e "\e[32mUSERNAME\e[0m"
echo    "---------"
        cat /etc/shadow | cut -d: -f1,8 | sed /:$/d > /tmp/expirelist.txt
        totalaccounts=`cat /tmp/expirelist.txt | wc -l`
        for((i=1; i<=$totalaccounts; i++ )); do
        tuserval=`head -n $i /tmp/expirelist.txt | tail -n 1`
        username=`echo $tuserval | cut -f1 -d:`
        userexp=`echo $tuserval | cut -f2 -d:`
        userexpireinseconds=$(( $userexp * 86400 ))
        todaystime=`date +%s`
        if [ $userexpireinseconds -gt $todaystime ] ; then
            echo $username
        fi
    done
	rm /tmp/expirelist.txt
}

function used_data(){
	myip=`ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0' | head -n1`
	myint=`ifconfig | grep -B1 "inet addr:$myip" | head -n1 | awk '{print $1}'`
	ifconfig $myint | grep "RX bytes" | sed -e 's/ *RX [a-z:0-9]*/Received: /g' | sed -e 's/TX [a-z:0-9]*/\nTransfered: /g'
}

clear
PS3='Please enter your choice: '
options=("Add User" "Renew User" "Delete User" "Current Connected Users" "User List" "Ram Status" "Users Not Expired" "Expired Users" "Monitor Dropbear & OpenSSH" "Used Data By Users" "Clear Cache Ram" "Quit")
select opt in "${options[@]}"
do
    case $opt in
        "Add User")
            read -p "Enter username: " uname
            read -p "Enter password: " pass
            read -p "Enter expiry date (YYYY-MM-DD): " expdate
	    create_user
	    break
            ;;
        "Renew User")
            read -p "Enter username to renew: " uname
            read -p "Enter expiry date (YYYY-MM-DD): " expdate
            renew_user
            break
            ;;
        "Delete User")
            read -p "Enter username to be removed: " uname
            delete_user
            break
            ;;
	"Current Connected Users")
            who -T | tr -s ' ' | cut -d ' ' -f 1-2 | sort -u
            break
            ;;		
	"User List")
            /root/status
            break
            ;;	
	"Ram Status")
	    free -h | grep -v + > /tmp/ramcache
            cat /tmp/ramcache | grep -v "Swap"
            break
            ;;	
	"Users Not Expired")
	    not_expired_users
	    break
	    ;;
	"Expired Users")
	    expired_users
	    break
	    ;;
        "Monitor Dropbear & OpenSSH")
	    dropmon
	    break
	    ;;
	"Used Data By Users")
	    used_data
            break
	     ;;
        "Clear Cache Ram")
	clear
	echo -e "\e[31mSebelum...\e[0m"
        free -h
	echo 1 > /proc/sys/vm/drop_caches
	sleep 1
	echo 2 > /proc/sys/vm/drop_caches
	sleep 1
	echo 3 > /proc/sys/vm/drop_caches && swapoff -a && swapon -a
	sleep 1
	echo ""
	echo -e "\e[32mSelepas...\e[0m"
	free -h
	echo "Berjaya..!!!Cache ram anda sudah di bersihkan."
        break
            ;;
        "Quit")
            break
            ;;
        *) echo invalid option;;
    esac
done
